" enable syntax highlighting
syntax enable

" set color scheme
"colorscheme badwolf
colorscheme space-vim-dark

let g:python_highlight_all = 1
let g:space_vim_dark_background = 235
"color space-vim-dark

set nocompatible

"
set background=dark

" show line numbers
set number

" set tabs to have 4 spaces
set ts=4

" indent when moving to the next line while writing code
set autoindent

" expand tabs into spaces
set expandtab

" when using the >> or << commands, shift lines by 4 spaces
set shiftwidth=4

" show a visual line under the cursor's current line
set cursorline

" show the matching part of the pair for [] {} and ()
set showmatch

" enable all Python syntax highlighting features
let python_highlight_all = 1

" Cursorline

highlight CursorLine cterm=underline
"""""""""""""""
" Key bindings
"""""""""""""""

" $/^ doesn't do anything
nnoremap ^ <nop>

"
nnoremap ; :

" Plug
call plug#begin()
Plug 'sheerun/vim-polyglot'
Plug 'vim-python/python-syntax'
call plug#end()
