" enable syntax highlighting
syntax enable

" Plug
call plug#begin(expand('~/.vim/plugged'))
Plug 'sheerun/vim-polyglot'
Plug 'vim-python/python-syntax'
Plug 'arcticicestudio/nord-vim'
Plug 'sonph/onehalf', { 'rtp': 'vim' }
Plug 'joshdick/onedark.vim'
Plug 'NLKNguyen/papercolor-theme'
call plug#end()

" set color scheme
colorscheme PaperColor
"colorscheme badwolf
"colorscheme onedark
"colorscheme space-vim-dark
"colorscheme nord
"colorscheme onehalfdark

"let g:airline_theme='onehalfdark'
" lightline
"let g:lightline = { 'colorscheme': 'onehalfdark' }
"let g:space_vim_dark_background = 235

"color space-vim-dark

"set nocompatible

"
"set t_Co=256

"
set background=dark

" show line numbers
set number

" set tabs to have 4 spaces
set ts=4

" indent when moving to the next line while writing code
set autoindent

" expand tabs into spaces
set expandtab

" when using the >> or << commands, shift lines by 4 spaces
set shiftwidth=4

" show a visual line under the cursor's current line
set cursorline

" show the matching part of the pair for [] {} and ()
set showmatch

" enable all Python syntax highlighting features
let python_highlight_all = 1

" Cursorline

highlight CursorLine cterm=underline
"""""""""""""""
" Key bindings
"""""""""""""""

" $/^ doesn't do anything
nnoremap ^ <nop>

"
nnoremap ; :
